#!/usr/bin/env bash
# Run on the LAPTOP, from the repo root. Builds the bridge's environment file
# from the credentials already in .env (HiveMQ) and .env.cloud (Supabase), so
# nothing has to be retyped. Output: ~/senseable-bridge.env (mode 600), outside
# the repository so it can never be committed.
set -euo pipefail
cd "$(dirname "$0")/../.."
OUT=${1:-$HOME/senseable-bridge.env}
get() { # last assignment of $1 in file $2, quotes stripped
  grep -E "^$1=" "$2" 2>/dev/null | tail -1 | cut -d= -f2- | sed -E 's/^"(.*)"$/\1/; s/^'"'"'(.*)'"'"'$/\1/'
}
need() { [ -n "$2" ] || { echo "missing $1 (looked in $3)" >&2; exit 1; }; }

APP=$(get CLOUD_DATABASE_URL .env.cloud);        need CLOUD_DATABASE_URL "$APP" .env.cloud
OWN=$(get CLOUD_DATABASE_URL_OWNER .env.cloud);  need CLOUD_DATABASE_URL_OWNER "$OWN" .env.cloud
MURL=$(get MQTT_URL .env);                       need MQTT_URL "$MURL" .env
case "$MURL" in *hivemq*) ;; *) echo "MQTT_URL in .env is '$MURL', not the HiveMQ cloud broker" >&2; exit 1 ;; esac

# systemd EnvironmentFile: double-quote every value, escaping \ and ", so a
# password with spaces or symbols survives intact.
kv() { local v=${2//\\/\\\\}; v=${v//\"/\\\"}; printf '%s="%s"\n' "$1" "$v"; }

umask 077
{
  echo "# Generated by deploy/bridge/make-env.sh on $(date -Iseconds). Secrets — keep mode 600."
  kv TIER "cloud"
  kv DATABASE_URL "$APP"
  kv DATABASE_URL_OWNER "$OWN"
  kv PG_SSL "no-verify"
  kv PG_POOL_MAX "5"
  kv PG_ADMIN_POOL_MAX "2"
  kv MQTT_URL "$MURL"
  for k in MQTT_USERNAME MQTT_PASSWORD MQTT_CLOUD_USERNAME MQTT_CLOUD_PASSWORD; do
    v=$(get "$k" .env); [ -n "$v" ] && kv "$k" "$v"
  done
  kv MQTT_CLIENT_ID "senseable-bridge"
  kv INGEST_STRICT_TENANT "true"
  kv AUTO_PROVISION "true"
  kv CLAIM_ON_CONNECT "false"
  kv HOST "127.0.0.1"
  kv PORT "4000"
  kv STATIC_DIR "/nonexistent"
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines, mode $(stat -c %a "$OUT"))"
